function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(5)=0;
    K_ss=(params(1)/(1/params(2)-(1-params(3))))^(1/(1-params(1)));
    ys_(3)=log(K_ss);
    Y_ss=K_ss^params(1);
    ys_(1)=log(Y_ss);
    I_ss=params(3)*K_ss;
    ys_(4)=log(I_ss);
    C_ss=Y_ss-I_ss;
    ys_(2)=log(C_ss);
    % Auxiliary equations
end
